# Site settings
title: Wanderson Policarpo
email: wpolicarpo@gmail.com
description: Wanderson Policarpo - Software Developer.
url: "https://www.policarpo.com.br"
name: Wanderson Policarpo
job: Software Developer
company:
  name: Avid Gaming
  site: https://www.avidgaming.com
location: Dublin, Ireland
credits: https://github.com/wpolicarpo/wpolicarpo.github.io#credits
gtag: "UA-19197679-1"

# Build settings
markdown: kramdown
